const usersDatabase = [
    {
        id: 1,
        name: 'Максим Коваленко',
        email: 'maksym.kovalenko@mail.com',
        age: 28,
    },
    {
        id: 2,
        name: 'Іван Шевченко',
        email: 'ivan.shevchenko@mail.com',
        age: 35,
    },
    {
        id: 3,
        name: 'Андрій Петренко',
        email: 'andrii.petrenko@mail.com',
        age: 42,
    },
    {
        id: 4,
        name: 'Олег Кравченко',
        email: 'oleg.kravchenko@mail.com',
        age: 31,
    },
    {
        id: 5,
        name: 'Сергій Бойченко',
        email: 'sergii.boychenko@mail.com',
        age: 48,
    },
    {
        id: 6,
        name: 'Дмитро Морозов',
        email: 'dmytro.morozov@mail.com',
        age: 26,
    },
    {
        id: 7,
        name: 'Василь Сидоренко',
        email: 'vasyl.sydorenko@mail.com',
        age: 51,
    },
    {
        id: 8,
        name: 'Павло Ковальчук',
        email: 'pavlo.kovalchuk@mail.com',
        age: 39,
    },
    { id: 9, name: 'Микола Іванов', email: 'mykola.ivanov@mail.com', age: 44 },
    {
        id: 10,
        name: 'Юрій Сергієнко',
        email: 'yurii.sergienko@mail.com',
        age: 33,
    },
    {
        id: 11,
        name: 'Геннадій Бондаренко',
        email: 'hennadii.bondarenko@mail.com',
        age: 55,
    },
    {
        id: 12,
        name: 'Петро Василенко',
        email: 'petro.vasylenko@mail.com',
        age: 29,
    },
    { id: 13, name: 'Віктор Герета', email: 'viktor.hereta@mail.com', age: 47 },
    {
        id: 14,
        name: 'Валентин Гриценко',
        email: 'valentyn.hrytsenko@mail.com',
        age: 36,
    },
    {
        id: 15,
        name: 'Станіслав Данилюк',
        email: 'stanislav.danyliuk@mail.com',
        age: 52,
    },
    { id: 16, name: 'Ігор Дяків', email: 'ihor.dyakiv@mail.com', age: 27 },
    {
        id: 17,
        name: 'Артем Зінкевич',
        email: 'artem.zinkevych@mail.com',
        age: 25,
    },
    {
        id: 18,
        name: 'Аркадій Зінчук',
        email: 'arkadii.zinchuk@mail.com',
        age: 58,
    },
    {
        id: 19,
        name: 'Борис Калениченко',
        email: 'borys.kalenichenko@mail.com',
        age: 43,
    },
    { id: 20, name: 'Глеб Канівець', email: 'hleb.kanivets@mail.com', age: 34 },
    {
        id: 21,
        name: 'Григорій Карпенко',
        email: 'hryhorii.karpenko@mail.com',
        age: 49,
    },
    {
        id: 22,
        name: 'Данило Кіщак',
        email: 'danylo.kishchak@mail.com',
        age: 30,
    },
    {
        id: 23,
        name: 'Еремій Кравець',
        email: 'yeremii.kravets@mail.com',
        age: 56,
    },
    { id: 24, name: 'Ефрем Лисак', email: 'efrem.lysak@mail.com', age: 38 },
    { id: 25, name: 'Захар Лютий', email: 'zakhar.lyutyi@mail.com', age: 45 },
    {
        id: 26,
        name: 'Зінов Маланюк',
        email: 'zinov.malanyuk@mail.com',
        age: 32,
    },
    {
        id: 27,
        name: 'Назар Малярчук',
        email: 'nazar.malyarchuk@mail.com',
        age: 28,
    },
    {
        id: 28,
        name: 'Конрад Марценко',
        email: 'konrad.martsenko@mail.com',
        age: 54,
    },
    {
        id: 29,
        name: 'Костянтин Микитенко',
        email: 'kostiantyn.mykytenko@mail.com',
        age: 41,
    },
    { id: 30, name: 'Лев Мостовий', email: 'lev.mostovyi@mail.com', age: 37 },
    { id: 31, name: 'Лука Мотуз', email: 'luka.motuz@mail.com', age: 26 },
    {
        id: 32,
        name: 'Матвій Нечипоренко',
        email: 'matvii.nechyporenko@mail.com',
        age: 50,
    },
    {
        id: 33,
        name: 'Мирослав Новак',
        email: 'myroslav.novak@mail.com',
        age: 29,
    },
    {
        id: 34,
        name: 'Модест Остапенко',
        email: 'modest.ostapenko@mail.com',
        age: 53,
    },
    {
        id: 35,
        name: 'Олександр Паламарчук',
        email: 'oleksandr.palamarchuk@mail.com',
        age: 40,
    },
    {
        id: 36,
        name: 'Орест Панасюк',
        email: 'orest.panasyuk@mail.com',
        age: 35,
    },
    {
        id: 37,
        name: 'Прокіп Панченко',
        email: 'prokip.panchenko@mail.com',
        age: 46,
    },
    { id: 38, name: 'Роман Панчук', email: 'roman.panchuk@mail.com', age: 31 },
    {
        id: 39,
        name: 'Сімеон Парфенко',
        email: 'simeon.parfenko@mail.com',
        age: 57,
    },
    {
        id: 40,
        name: 'Софрон Павличенко',
        email: 'sofron.pavlychenko@mail.com',
        age: 27,
    },
    { id: 41, name: 'Тарас Павлюк', email: 'taras.pavliuk@mail.com', age: 44 },
    {
        id: 42,
        name: 'Телесфор Панько',
        email: 'telesfor.panko@mail.com',
        age: 33,
    },
    { id: 43, name: 'Федір Позняк', email: 'fedir.poznyak@mail.com', age: 48 },
    { id: 44, name: 'Федот Приймак', email: 'fedot.priymak@mail.com', age: 39 },
    {
        id: 45,
        name: 'Феодосій Пастернак',
        email: 'feodosii.pasternак@mail.com',
        age: 52,
    },
    { id: 46, name: 'Філіп Рева', email: 'filip.reva@mail.com', age: 25 },
    { id: 47, name: 'Філат Рибалка', email: 'filat.rybalka@mail.com', age: 51 },
    { id: 48, name: 'Франц Рудик', email: 'franz.rudyk@mail.com', age: 28 },
    { id: 49, name: 'Харитон Рудь', email: 'kharyton.rud@mail.com', age: 55 },
    { id: 50, name: 'Хома Рудяк', email: 'khoma.rudyak@mail.com', age: 42 },
    {
        id: 51,
        name: 'Христофор Сахно',
        email: 'khrystophor.sakhno@mail.com',
        age: 36,
    },
    {
        id: 52,
        name: 'Чеслав Свистун',
        email: 'cheslav.svystun@mail.com',
        age: 30,
    },
    {
        id: 53,
        name: 'Юлій Селіванов',
        email: 'yulii.selivanov@mail.com',
        age: 47,
    },
    {
        id: 54,
        name: 'Ярослав Семененко',
        email: 'yaroslav.semenenko@mail.com',
        age: 34,
    },
    {
        id: 55,
        name: 'Анатолій Синиця',
        email: 'anatolii.synytsia@mail.com',
        age: 49,
    },
    {
        id: 56,
        name: 'Владислав Сірий',
        email: 'vladyslav.siryi@mail.com',
        age: 29,
    },
    { id: 57, name: 'Вадим Слюсар', email: 'vadym.sliusar@mail.com', age: 45 },
    { id: 58, name: 'Валерій Сокур', email: 'valerii.sokur@mail.com', age: 38 },
    {
        id: 59,
        name: 'Вальтер Солодкий',
        email: 'valter.solodkyi@mail.com',
        age: 54,
    },
    {
        id: 60,
        name: 'Віталій Сопуленко',
        email: 'vitalii.sopulenko@mail.com',
        age: 26,
    },
    {
        id: 61,
        name: 'Геращенко Сорока',
        email: 'herashchenko.soroka@mail.com',
        age: 43,
    },
    {
        id: 62,
        name: 'Геліодор Стельмах',
        email: 'heliodor.stelmakh@mail.com',
        age: 56,
    },
    { id: 63, name: 'Георгій Стус', email: 'heorhi.stus@mail.com', age: 32 },
    {
        id: 64,
        name: 'Гордій Супруненко',
        email: 'hordii.suprunenko@mail.com',
        age: 41,
    },
    {
        id: 65,
        name: 'Давид Суходоля',
        email: 'david.sukhodoliя@mail.com',
        age: 27,
    },
    {
        id: 66,
        name: 'Дарій Твердохліб',
        email: 'darii.tverdokhlib@mail.com',
        age: 50,
    },
    {
        id: 67,
        name: 'Демʼян Тесленко',
        email: 'demian.teslenko@mail.com',
        age: 35,
    },
    {
        id: 68,
        name: 'Денис Титаренко',
        email: 'denys.tytarenko@mail.com',
        age: 31,
    },
    {
        id: 69,
        name: 'Демʼютій Ткачук',
        email: 'demiutii.tkachuk@mail.com',
        age: 46,
    },
    {
        id: 70,
        name: 'Дорофей Толочко',
        email: 'dorofei.tolochko@mail.com',
        age: 44,
    },
    {
        id: 71,
        name: 'Дорофій Толочка',
        email: 'dorofii.tolochka@mail.com',
        age: 37,
    },
    {
        id: 72,
        name: 'Євгеній Торосян',
        email: 'yevhenii.torosyan@mail.com',
        age: 52,
    },
    {
        id: 73,
        name: 'Єльчиков Триліський',
        email: 'yelchykov.triliski@mail.com',
        age: 28,
    },
    {
        id: 74,
        name: 'Захарій Удовенко',
        email: 'zakharij.udovenko@mail.com',
        age: 51,
    },
    {
        id: 75,
        name: 'Зінон Удовиченко',
        email: 'zinon.udovychenko@mail.com',
        age: 39,
    },
    { id: 76, name: 'Іванів Улько', email: 'ivaniv.ulko@mail.com', age: 25 },
    { id: 77, name: 'Ідей Унич', email: 'idey.unych@mail.com', age: 48 },
    {
        id: 78,
        name: 'Йосип Устименко',
        email: 'yosyp.ustymenko@mail.com',
        age: 30,
    },
    {
        id: 79,
        name: 'Йосифат Фесенко',
        email: 'yosyfat.fesenko@mail.com',
        age: 55,
    },
    {
        id: 80,
        name: 'Каленник Філіпенко',
        email: 'kalenyk.filipenko@mail.com',
        age: 34,
    },
    { id: 81, name: 'Карп Філіпов', email: 'karp.filipov@mail.com', age: 47 },
    {
        id: 82,
        name: 'Касіян Франко',
        email: 'kasijan.franko@mail.com',
        age: 29,
    },
    { id: 83, name: 'Киріяк Хома', email: 'kiriak.khoma@mail.com', age: 53 },
    {
        id: 84,
        name: 'Климент Хомик',
        email: 'klyment.khomyk@mail.com',
        age: 40,
    },
    {
        id: 85,
        name: 'Кліщак Цимбалюк',
        email: 'klishchak.tsymbaliuk@mail.com',
        age: 36,
    },
    {
        id: 86,
        name: 'Кодратій Цюцюра',
        email: 'kodratii.tsyutsyura@mail.com',
        age: 42,
    },
    {
        id: 87,
        name: 'Кондратій Черненко',
        email: 'kondratii.chernenko@mail.com',
        age: 33,
    },
    {
        id: 88,
        name: 'Кор Чеховський',
        email: 'kor.chekhovskyi@mail.com',
        age: 49,
    },
    {
        id: 89,
        name: 'Корнелій Чумак',
        email: 'kornelij.chumak@mail.com',
        age: 26,
    },
    {
        id: 90,
        name: 'Корніль Шавель',
        email: 'kornyl.shavel@mail.com',
        age: 54,
    },
    {
        id: 91,
        name: 'Лаврентій Шамрай',
        email: 'lavrentii.shamray@mail.com',
        age: 38,
    },
    {
        id: 92,
        name: 'Ларіон Шевернога',
        email: 'larion.shevernoha@mail.com',
        age: 27,
    },
    {
        id: 93,
        name: 'Леонід Шевчак',
        email: 'leonid.shevchak@mail.com',
        age: 45,
    },
    {
        id: 94,
        name: 'Линар Шеремет',
        email: 'lynar.sheremet@mail.com',
        age: 32,
    },
    { id: 95, name: 'Лупій Шкарлет', email: 'lupii.skarlет@mail.com', age: 50 },
    {
        id: 96,
        name: 'Лучіян Шостак',
        email: 'luchiian.shostak@mail.com',
        age: 41,
    },
    {
        id: 97,
        name: 'Люстарник Юденко',
        email: 'lyustarnyk.yudenko@mail.com',
        age: 28,
    },
    { id: 98, name: 'Мавродій Юнь', email: 'mavrodii.yun@mail.com', age: 57 },
    { id: 99, name: 'Макар Юрасов', email: 'makar.yurasov@mail.com', age: 35 },
    {
        id: 100,
        name: 'Мелхіседек Щур',
        email: 'melkhisedek.shchur@mail.com',
        age: 44,
    },
    {
        id: 101,
        name: 'Максим Коваленко',
        email: 'maksym.kovalenko.101@mail.com',
        age: 28,
    },
    {
        id: 102,
        name: 'Максим Петренко',
        email: 'maksym.petrenko.102@mail.com',
        age: 35,
    },
    {
        id: 103,
        name: 'Максим Шевченко',
        email: 'maksym.shevchenko.103@mail.com',
        age: 42,
    },
    {
        id: 104,
        name: 'Максим Морозов',
        email: 'maksym.morozov.104@mail.com',
        age: 31,
    },
    {
        id: 105,
        name: 'Максим Сидоренко',
        email: 'maksym.sydorenko.105@mail.com',
        age: 48,
    },
    {
        id: 106,
        name: 'Іван Бойченко',
        email: 'ivan.boychenko.106@mail.com',
        age: 26,
    },
    {
        id: 107,
        name: 'Іван Кравченко',
        email: 'ivan.kravchenko.107@mail.com',
        age: 51,
    },
    {
        id: 108,
        name: 'Іван Ковальчук',
        email: 'ivan.kovalchuk.108@mail.com',
        age: 39,
    },
    {
        id: 109,
        name: 'Іван Сергієнко',
        email: 'ivan.sergienko.109@mail.com',
        age: 44,
    },
    {
        id: 110,
        name: 'Іван Василенко',
        email: 'ivan.vasylenko.110@mail.com',
        age: 33,
    },
    {
        id: 111,
        name: 'Андрій Герета',
        email: 'andrii.hereta.111@mail.com',
        age: 55,
    },
    {
        id: 112,
        name: 'Андрій Гриценко',
        email: 'andrii.hrytsenko.112@mail.com',
        age: 29,
    },
    {
        id: 113,
        name: 'Андрій Бондаренко',
        email: 'andrii.bondarenko.113@mail.com',
        age: 47,
    },
    {
        id: 114,
        name: 'Андрій Данилюк',
        email: 'andrii.danyliuk.114@mail.com',
        age: 36,
    },
    {
        id: 115,
        name: 'Андрій Дяків',
        email: 'andrii.dyakiv.115@mail.com',
        age: 52,
    },
    {
        id: 116,
        name: 'Сергій Зінкевич',
        email: 'sergii.zinkevych.116@mail.com',
        age: 27,
    },
    {
        id: 117,
        name: 'Сергій Зінчук',
        email: 'sergii.zinchuk.117@mail.com',
        age: 25,
    },
    {
        id: 118,
        name: 'Сергій Калениченко',
        email: 'sergii.kalenichenko.118@mail.com',
        age: 58,
    },
    {
        id: 119,
        name: 'Сергій Канівець',
        email: 'sergii.kanivets.119@mail.com',
        age: 43,
    },
    {
        id: 120,
        name: 'Сергій Карпенко',
        email: 'sergii.karpenko.120@mail.com',
        age: 34,
    },
    {
        id: 121,
        name: 'Олег Кіщак',
        email: 'oleg.kishchak.121@mail.com',
        age: 49,
    },
    {
        id: 122,
        name: 'Олег Кравець',
        email: 'oleg.kravets.122@mail.com',
        age: 30,
    },
    { id: 123, name: 'Олег Лисак', email: 'oleg.lysak.123@mail.com', age: 56 },
    { id: 124, name: 'Олег Лютий', email: 'oleg.lyutyi.124@mail.com', age: 38 },
    {
        id: 125,
        name: 'Олег Маланюк',
        email: 'oleg.malanyuk.125@mail.com',
        age: 45,
    },
    {
        id: 126,
        name: 'Дмитро Малярчук',
        email: 'dmytro.malyarchuk.126@mail.com',
        age: 32,
    },
    {
        id: 127,
        name: 'Дмитро Марценко',
        email: 'dmytro.martsenko.127@mail.com',
        age: 28,
    },
    {
        id: 128,
        name: 'Дмитро Микитенко',
        email: 'dmytro.mykytenko.128@mail.com',
        age: 54,
    },
    {
        id: 129,
        name: 'Дмитро Мостовий',
        email: 'dmytro.mostovyi.129@mail.com',
        age: 41,
    },
    {
        id: 130,
        name: 'Дмитро Мотуз',
        email: 'dmytro.motuz.130@mail.com',
        age: 37,
    },
    {
        id: 131,
        name: 'Павло Нечипоренко',
        email: 'pavlo.nechyporenko.131@mail.com',
        age: 26,
    },
    {
        id: 132,
        name: 'Павло Новак',
        email: 'pavlo.novak.132@mail.com',
        age: 50,
    },
    {
        id: 133,
        name: 'Павло Остапенко',
        email: 'pavlo.ostapenko.133@mail.com',
        age: 29,
    },
    {
        id: 134,
        name: 'Павло Паламарчук',
        email: 'pavlo.palamarchuk.134@mail.com',
        age: 53,
    },
    {
        id: 135,
        name: 'Павло Панасюк',
        email: 'pavlo.panasyuk.135@mail.com',
        age: 40,
    },
    {
        id: 136,
        name: 'Микола Панченко',
        email: 'mykola.panchenko.136@mail.com',
        age: 35,
    },
    {
        id: 137,
        name: 'Микола Панчук',
        email: 'mykola.panchuk.137@mail.com',
        age: 46,
    },
    {
        id: 138,
        name: 'Микола Парфенко',
        email: 'mykola.parfenko.138@mail.com',
        age: 31,
    },
    {
        id: 139,
        name: 'Микола Павличенко',
        email: 'mykola.pavlychenko.139@mail.com',
        age: 57,
    },
    {
        id: 140,
        name: 'Микола Павлюк',
        email: 'mykola.pavliuk.140@mail.com',
        age: 27,
    },
    {
        id: 141,
        name: 'Юрій Панько',
        email: 'yurii.panko.141@mail.com',
        age: 44,
    },
    {
        id: 142,
        name: 'Юрій Позняк',
        email: 'yurii.poznyak.142@mail.com',
        age: 33,
    },
    {
        id: 143,
        name: 'Юрій Приймак',
        email: 'yurii.priymak.143@mail.com',
        age: 48,
    },
    {
        id: 144,
        name: 'Юрій Пастернак',
        email: 'yurii.pasternак.144@mail.com',
        age: 39,
    },
    { id: 145, name: 'Юрій Рева', email: 'yurii.reva.145@mail.com', age: 52 },
    {
        id: 146,
        name: 'Геннадій Рибалка',
        email: 'hennadii.rybalka.146@mail.com',
        age: 25,
    },
    {
        id: 147,
        name: 'Геннадій Рудик',
        email: 'hennadii.rudyk.147@mail.com',
        age: 51,
    },
    {
        id: 148,
        name: 'Геннадій Рудь',
        email: 'hennadii.rud.148@mail.com',
        age: 28,
    },
    {
        id: 149,
        name: 'Геннадій Рудяк',
        email: 'hennadii.rudyak.149@mail.com',
        age: 55,
    },
    {
        id: 150,
        name: 'Геннадій Сахно',
        email: 'hennadii.sakhno.150@mail.com',
        age: 42,
    },
    {
        id: 151,
        name: 'Петро Свистун',
        email: 'petro.svystun.151@mail.com',
        age: 36,
    },
    {
        id: 152,
        name: 'Петро Селіванов',
        email: 'petro.selivanov.152@mail.com',
        age: 30,
    },
    {
        id: 153,
        name: 'Петро Семененко',
        email: 'petro.semenenko.153@mail.com',
        age: 47,
    },
    {
        id: 154,
        name: 'Петро Синиця',
        email: 'petro.synytsia.154@mail.com',
        age: 34,
    },
    {
        id: 155,
        name: 'Петро Сірий',
        email: 'petro.siryi.155@mail.com',
        age: 49,
    },
    {
        id: 156,
        name: 'Віктор Слюсар',
        email: 'viktor.sliusar.156@mail.com',
        age: 29,
    },
    {
        id: 157,
        name: 'Віктор Сокур',
        email: 'viktor.sokur.157@mail.com',
        age: 45,
    },
    {
        id: 158,
        name: 'Віктор Солодкий',
        email: 'viktor.solodkyi.158@mail.com',
        age: 38,
    },
    {
        id: 159,
        name: 'Віктор Сопуленко',
        email: 'viktor.sopulenko.159@mail.com',
        age: 54,
    },
    {
        id: 160,
        name: 'Віктор Сорока',
        email: 'viktor.soroka.160@mail.com',
        age: 26,
    },
    {
        id: 161,
        name: 'Валентин Стельмах',
        email: 'valentyn.stelmakh.161@mail.com',
        age: 43,
    },
    {
        id: 162,
        name: 'Валентин Стус',
        email: 'valentyn.stus.162@mail.com',
        age: 56,
    },
    {
        id: 163,
        name: 'Валентин Супруненко',
        email: 'valentyn.suprunenko.163@mail.com',
        age: 32,
    },
    {
        id: 164,
        name: 'Валентин Суходоля',
        email: 'valentyn.sukhodoliя.164@mail.com',
        age: 41,
    },
    {
        id: 165,
        name: 'Валентин Твердохліб',
        email: 'valentyn.tverdokhlib.165@mail.com',
        age: 27,
    },
    {
        id: 166,
        name: 'Станіслав Тесленко',
        email: 'stanislav.teslenko.166@mail.com',
        age: 50,
    },
    {
        id: 167,
        name: 'Станіслав Титаренко',
        email: 'stanislav.tytarenko.167@mail.com',
        age: 35,
    },
    {
        id: 168,
        name: 'Станіслав Ткачук',
        email: 'stanislav.tkachuk.168@mail.com',
        age: 31,
    },
    {
        id: 169,
        name: 'Станіслав Толочко',
        email: 'stanislav.tolochko.169@mail.com',
        age: 46,
    },
    {
        id: 170,
        name: 'Станіслав Толочка',
        email: 'stanislav.tolochka.170@mail.com',
        age: 44,
    },
    {
        id: 171,
        name: 'Ігор Торосян',
        email: 'ihor.torosyan.171@mail.com',
        age: 37,
    },
    {
        id: 172,
        name: 'Ігор Триліський',
        email: 'ihor.triliski.172@mail.com',
        age: 52,
    },
    {
        id: 173,
        name: 'Ігор Удовенко',
        email: 'ihor.udovenko.173@mail.com',
        age: 28,
    },
    {
        id: 174,
        name: 'Ігор Удовиченко',
        email: 'ihor.udovychenko.174@mail.com',
        age: 51,
    },
    { id: 175, name: 'Ігор Улько', email: 'ihor.ulko.175@mail.com', age: 39 },
    { id: 176, name: 'Артем Унич', email: 'artem.unych.176@mail.com', age: 25 },
    {
        id: 177,
        name: 'Артем Устименко',
        email: 'artem.ustymenko.177@mail.com',
        age: 48,
    },
    {
        id: 178,
        name: 'Артем Фесенко',
        email: 'artem.fesenko.178@mail.com',
        age: 30,
    },
    {
        id: 179,
        name: 'Артем Філіпенко',
        email: 'artem.filipenko.179@mail.com',
        age: 55,
    },
    {
        id: 180,
        name: 'Артем Франко',
        email: 'artem.franko.180@mail.com',
        age: 34,
    },
    {
        id: 181,
        name: 'Аркадій Хома',
        email: 'arkadii.khoma.181@mail.com',
        age: 47,
    },
    {
        id: 182,
        name: 'Аркадій Хомик',
        email: 'arkadii.khomyk.182@mail.com',
        age: 29,
    },
    {
        id: 183,
        name: 'Аркадій Цимбалюк',
        email: 'arkadii.tsymbaliuk.183@mail.com',
        age: 53,
    },
    {
        id: 184,
        name: 'Аркадій Цюцюра',
        email: 'arkadii.tsyutsyura.184@mail.com',
        age: 40,
    },
    {
        id: 185,
        name: 'Аркадій Черненко',
        email: 'arkadii.chernenko.185@mail.com',
        age: 36,
    },
    {
        id: 186,
        name: 'Борис Чеховський',
        email: 'borys.chekhovskyi.186@mail.com',
        age: 42,
    },
    {
        id: 187,
        name: 'Борис Чумак',
        email: 'borys.chumak.187@mail.com',
        age: 33,
    },
    {
        id: 188,
        name: 'Борис Шавель',
        email: 'borys.shavel.188@mail.com',
        age: 49,
    },
    {
        id: 189,
        name: 'Борис Шамрай',
        email: 'borys.shamray.189@mail.com',
        age: 26,
    },
    {
        id: 190,
        name: 'Борис Шевернога',
        email: 'borys.shevernoha.190@mail.com',
        age: 54,
    },
    {
        id: 191,
        name: 'Глеб Шевчак',
        email: 'hleb.shevchak.191@mail.com',
        age: 38,
    },
    {
        id: 192,
        name: 'Глеб Шеремет',
        email: 'hleb.sheremet.192@mail.com',
        age: 27,
    },
    {
        id: 193,
        name: 'Глеб Шкарлет',
        email: 'hleb.skarlет.193@mail.com',
        age: 45,
    },
    {
        id: 194,
        name: 'Глеб Шостак',
        email: 'hleb.shostak.194@mail.com',
        age: 32,
    },
    {
        id: 195,
        name: 'Глеб Юденко',
        email: 'hleb.yudenko.195@mail.com',
        age: 50,
    },
    {
        id: 196,
        name: 'Григорій Юнь',
        email: 'hryhorii.yun.196@mail.com',
        age: 41,
    },
    {
        id: 197,
        name: 'Григорій Юрасов',
        email: 'hryhorii.yurasov.197@mail.com',
        age: 28,
    },
    {
        id: 198,
        name: 'Григорій Щур',
        email: 'hryhorii.shchur.198@mail.com',
        age: 57,
    },
    {
        id: 199,
        name: 'Данило Щепель',
        email: 'danylo.shchepel.199@mail.com',
        age: 35,
    },
    {
        id: 200,
        name: 'Данило Щоденко',
        email: 'danylo.shchodenko.200@mail.com',
        age: 44,
    },
];

// Получить всех пользователей
export function fetchAll() {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve([...usersDatabase]);
        }, 1000);
    });
}

// Получить пользователей по имени
export async function fetchAllByName(searchName) {
    return new Promise((resolve) => {
        setTimeout(() => {
            if (!searchName || !searchName.trim()) {
                resolve([...usersDatabase]);
                return;
            }

            const filteredUsers = usersDatabase.filter((user) =>
                user.name.toLowerCase().includes(searchName.toLowerCase())
            );

            resolve(filteredUsers);
        }, 10);
    });
}
